version: '2.2'
services:
  redis:
    image: redis:6.0.16
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pastebin-x

volumes:
  redis_data:
    driver: local

networks:
  pastebin-x:
    driver: bridge